### ISSUE TITLE
prefer-flat-map warns about and auto-fixes the wrong order of flat()/map() calls

### ISSUE THREAD

**Issue by arild-haugstad** [freaktechnik/eslint-plugin-array-func#25]
According to MDN --- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap --- and my quick tests in NodeJS and Firefox, `flatMap()` is equivalent with running `flat()` on the output of `map()`, not with running `map()` on the output of `flat()` which the rule warns about and rewrites from...

E.g. `console.log([[1, 2], [3, 4]].flat().map((x) => x * 2));` outputs `[2, 4, 6, 8]`, but is "autofixed" to `console.log([[1, 2], [3, 4]].flatMap((x) => x * 2));` which outputs `[NaN, NaN]`.

**Comment by freaktechnik** [comment]
Hm, I remember reversing that order multiple times due to being confused about what flatMap actually did. Thanks for pointing this out.

**Comment by arild-haugstad** [comment]
I assume that the use case for `flatMap()` would be for transformations where some of the elements in the input array may become several elements in the output array; where `flatMap()` is both faster and conceptually "cleaner" that `map()` followed by `flat()` in that it doesn't construct some nonsense intermediate array --- that's significantly more useful than the other way around ;-)
