### ISSUE TITLE
autofix for avoid-reverse (still) has unsafe edge case

### ISSUE THREAD

**Issue by arild-haugstad** [freaktechnik/eslint-plugin-array-func#26]
`indexOf` and `lastIndexOf` return -1 for "not found"; after autofix, the resulting code return the array length instead for "not found":

`const arr = ["a", "b", "c", "d", "e"]; console.log(arr.reverse().indexOf("f"));`
becomes
`const arr = ["a", "b", "c", "d", "e"]; console.log(arr.length - 1 - arr.lastIndexOf("f"));`
printing 5 rather than -1.

If `reverse` + `indexOf` is run on an array literal, autofix will give broken output --- though I don't know whether this kind of input should be worth caring about:

`console.log(["a", "b", "c", "d", "e"].reverse().indexOf("a"));`
becomes
`console.log(undefined.length - 1 - ["a", "b", "c", "d", "e"].lastIndexOf("a"));`

**Comment by freaktechnik** [comment]
Ugh, you're right. I guess the real solution is just to avoid lastIndexOf all together.

> though I don't know whether this kind of input should be worth caring about

I think there should actually be a rule to not allow "unnecessary" operations on literals, like reversing or empty slices.
