### ISSUE TITLE
New rule: unnecessary filter then find 

### ISSUE THREAD

**Issue by golopot** [freaktechnik/eslint-plugin-array-func#29]
```javascript
// invalid:
arr
  .filter(x => p(x))
  .find(x => q(x))

// valid
arr
  .find(x => p(x) && q(x))
// Outputs are equivalent (I think). Also potentially short-circuits faster.  
```

The fix is not always safe. For example when `p` and `q` has side effects that depends on the order of execution, or when `p` or `q` throws errors.

**Comment by vegerot** [comment]
Maybe also doing
```javascript
arr
  .filter(x=>p(x))[0]
```
would be something valid to be caught by this

**Comment by freaktechnik** [comment]
> Maybe also doing
> 
> ```js
> arr
>   .filter(x=>p(x))[0]
> ```
> 
> would be something valid to be caught by this

This case is already available with [unicorn/prefer-array-find](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-array-find.md). (That plugin also offers a prefer-flat-map rule)
