### ISSUE TITLE
New release with flat config

### ISSUE THREAD

**Issue by brettz9** [freaktechnik/eslint-plugin-array-func#456]
Any chance you might make at least an alpha/beta release to include the flat config support?

Thanks!

**Comment by freaktechnik** [comment]
I've been meaning to push the current state out as a release for a while now but haven't gotten around to it yet. I hope to get it done by the end of the month.

**Comment by freaktechnik** [comment]
Please enjoy 5.0.1

**Comment by boris-petrov** [comment]
Is it possible to use the new release with the old-style config? If not, can I switch to the flat config and expect everything (including all my other plugins) to work as before?

**Comment by freaktechnik** [comment]
It does not work with the old config, as the release notes say. The official eslint guide includes how to use plugins that don't provide flat configs yet in a flat config file: https://eslint.org/docs/latest/use/configure/migration-guide
