### ISSUE TITLE
Array.from isn't faster than the spread element

### ISSUE THREAD

**Issue by fregante** [freaktechnik/eslint-plugin-array-func#69]
The readme says:

> Use `Array.from` instead of `[...iterable]` for performance benefits.

but it doesn't appear to be correct.

https://www.measurethat.net/Benchmarks/Show/1721/0/arrayfrom-vs-spread

`Array.from` is just different in that it works on array-like objects, but it's actually ever-so-slightly slower in all browsers I tested.

**Comment by freaktechnik** [comment]
At the time I had initially written the rule there was a performance benefit in some browser, though it is probably a good point to remove that now. It is after all just a style choice at this point (apart from the slight difference in behavior of the mapping function with typed arrays)
